import {
  ChevronDown,
  ChevronRight,
  Sun,
  Moon,
  Plus,
  MoreHorizontal,
  GripVertical,
  Settings,
  LayoutGrid,
  List,
  Download,
  CheckSquare,
  MessageSquare,
  Search,
  Users,
  PanelLeft,
  ChevronsLeft,
  ChevronsRight,
  X,
  PlusCircle,
  FileText,
  Trash2,
  Copy,
  Archive,
  Star,
  Columns,
  Minus,
  BarChart2,
  Sparkles,
  Loader2,
} from 'lucide-react';

export const Icons = {
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  sun: Sun,
  moon: Moon,
  plus: Plus,
  plusCircle: PlusCircle,
  more: MoreHorizontal,
  grip: GripVertical,
  settings: Settings,
  board: LayoutGrid,
  backlog: List,
  download: Download,
  checklist: CheckSquare,
  comments: MessageSquare,
  search: Search,
  users: Users,
  sidebar: PanelLeft,
  sidebarOpen: ChevronsLeft,
  sidebarClose: ChevronsRight,
  close: X,
  file: FileText,
  trash: Trash2,
  copy: Copy,
  archive: Archive,
  star: Star,
  columns: Columns,
  minus: Minus,
  metrics: BarChart2,
  sparkles: Sparkles,
  loader: Loader2,
};
